### ISSUE TITLE
UX/UI research on homepage

### ISSUE THREAD

**Issue by thasup** [peuan/travelmate-web#24]
## Task

- [ ] Research our competitor's homepage flow
- [ ] Research our competitor's UI design
- [ ] design UX/UI design for our homepage
