### ISSUE TITLE
Implement the Authentication UI (Login/Register) screen.

### ISSUE THREAD

**Issue by thasup** [peuan/travelmate-web#25]
## Tasks 

- [ ] Create a reusable component for the login/register modal.
- [ ] Create the login screen.
- [ ] Create the register screen.
- [ ] Create the forgot password screen.
- [ ] Add validation to the form.
- [ ] Integrate the login screen with the API.
- [ ] Integrate the register screen with the API.
- [ ] Integrate the forgot password screen with the API.
