### ISSUE TITLE
Competitor Audit Report

### ISSUE THREAD

**Issue by thasup** [peuan/travelmate-web#26]
## Task

- [ ] Identify who are our direct and indirect competitors
- [ ] Conduct a competitor audit report
- [ ] Conduct a competitor report
